# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AboutRegion.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AboutRegion(object):
    def setupUi(self, AboutRegion):
        AboutRegion.setObjectName("AboutRegion")
        AboutRegion.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(AboutRegion)
        self.centralwidget.setObjectName("centralwidget")
        self.HistoryButton = QtWidgets.QPushButton(self.centralwidget)
        self.HistoryButton.setGeometry(QtCore.QRect(60, 70, 121, 61))
        self.HistoryButton.setObjectName("HistoryButton")
        self.EventshButton = QtWidgets.QPushButton(self.centralwidget)
        self.EventshButton.setGeometry(QtCore.QRect(610, 70, 121, 61))
        self.EventshButton.setObjectName("EventshButton")
        self.HistoryFrame = QtWidgets.QFrame(self.centralwidget)
        self.HistoryFrame.setGeometry(QtCore.QRect(50, 130, 701, 381))
        self.HistoryFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HistoryFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HistoryFrame.setObjectName("HistoryFrame")
        self.HistoryTextEdit = QtWidgets.QTextEdit(self.HistoryFrame)
        self.HistoryTextEdit.setGeometry(QtCore.QRect(10, 10, 671, 361))
        self.HistoryTextEdit.setObjectName("HistoryTextEdit")
        self.EventsFrame = QtWidgets.QFrame(self.centralwidget)
        self.EventsFrame.setGeometry(QtCore.QRect(49, 129, 701, 381))
        self.EventsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.EventsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.EventsFrame.setObjectName("EventsFrame")
        self.EventsTable = QtWidgets.QTableWidget(self.EventsFrame)
        self.EventsTable.setGeometry(QtCore.QRect(10, 10, 671, 361))
        self.EventsTable.setObjectName("EventsTable")
        self.EventsTable.setColumnCount(4)
        self.EventsTable.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventsTable.setItem(5, 3, item)
        AboutRegion.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AboutRegion)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        AboutRegion.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AboutRegion)
        self.statusbar.setObjectName("statusbar")
        AboutRegion.setStatusBar(self.statusbar)

        self.retranslateUi(AboutRegion)
        QtCore.QMetaObject.connectSlotsByName(AboutRegion)

    def retranslateUi(self, AboutRegion):
        _translate = QtCore.QCoreApplication.translate
        AboutRegion.setWindowTitle(_translate("AboutRegion", "MainWindow"))
        self.HistoryButton.setText(_translate("AboutRegion", "История"))
        self.EventshButton.setText(_translate("AboutRegion", "События"))
        self.HistoryTextEdit.setHtml(_translate("AboutRegion", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Кубань начинается с поля - раздольного и неоглядного. От донских степей до хребтов Кавказа, словно чаша, слегка наклоненная навстречу влажным ветрам Черноморья, раскинулись просторы хлебного края. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Испокон веков влекли и манили к себе широкие нивы по берегам быстрой и своенравной реки, давшей имя этому краю. Кубанская земля слышала рокот копыт сарматской и половецкой конниц, звон золотых монет в кожаных поясах греческих колонистов и генуэзских купцов, могучую поступь русских дружин Тмутаракани, дикие пиры татарских орд и османских турок. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Терзаемые то одними, то другими колонизаторами, долгие годы вели кровопролитную и неравную борьбу аборигены Кубани - адыгейские племена. Иноземные завоеватели, особенно татары и турки, грабили землю, разоряли адыгейские аулы, захватывали и продавали в рабство непокорных горцев, во все гаремы Востока увозили черкесских женщин. Измученные грабежами и насилием, адыги, или, как тогда их называли, черкесы, искали защиты и помощи у своего могущественного северного брата - русского народа. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">В 1552 году в Москву к царю Ивану IV прибыли черкесские послы с просьбой о присоединении Адыгеи к России. Приняв адыгов в свое подданство, Россия помогла изгнать турок из Приазовья. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Черкесский князь Темрюк выдал свою дочь замуж за Ивана Грозного, основал на месте татаро-турецкой крепости Тумнев свой &quot;стольный&quot; город Темрюк. Но не успела осесть пыль за русскими полками, ушедшими с Кубани, как вновь налетели татары и турки и, отодвинув владения черкесов далеко на восток, разрушили Темрюк, на его месте воздвигли свою крепость Адис, из которой их орды совершали опустошительные набеги на владения государства Российского. В 1720 году русские войска вступили на Кубань, чтобы примерно покарать &quot;басурман&quot; и отбить у них охоту разбойничать в российских землях. Но отдельные, даже успешные операции не могли решить спора. Завязалась длительная война с Турцией. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Планомерное заселение Кубани российскими подданными началось после двух русско-турецких войн XVIII века. В 1778 году командующий Кавказским корпусом А.В.Суворов, прибыв на Кубань, начал укреплять южные границы государства. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Прославившемуся в борьбе с турками Черноморскому войску (бывшим запорожцам) Екатерина II даровала 30 июня 1792 года земли Таманского полуострова с окрестностями с целью охраны новых южных границ России. Первая партия строевых казаков во главе с С. Белым прибыла сюда морем и 25 августа 1792 года высадилась в Тамани. Десятилетия спустя - уже после отмены крепостного права - двинулись на Кубань тысячи крестьян из центральных губерний России... </span></p></body></html>"))
        item = self.EventsTable.verticalHeaderItem(0)
        item.setText(_translate("AboutRegion", "1"))
        item = self.EventsTable.verticalHeaderItem(1)
        item.setText(_translate("AboutRegion", "2"))
        item = self.EventsTable.verticalHeaderItem(2)
        item.setText(_translate("AboutRegion", "3"))
        item = self.EventsTable.verticalHeaderItem(3)
        item.setText(_translate("AboutRegion", "4"))
        item = self.EventsTable.verticalHeaderItem(4)
        item.setText(_translate("AboutRegion", "5"))
        item = self.EventsTable.verticalHeaderItem(5)
        item.setText(_translate("AboutRegion", "6"))
        item = self.EventsTable.horizontalHeaderItem(0)
        item.setText(_translate("AboutRegion", "Название"))
        item = self.EventsTable.horizontalHeaderItem(1)
        item.setText(_translate("AboutRegion", "Описание"))
        item = self.EventsTable.horizontalHeaderItem(2)
        item.setText(_translate("AboutRegion", "Дата проведения"))
        item = self.EventsTable.horizontalHeaderItem(3)
        item.setText(_translate("AboutRegion", "Сайт"))
        __sortingEnabled = self.EventsTable.isSortingEnabled()
        self.EventsTable.setSortingEnabled(False)
        item = self.EventsTable.item(0, 0)
        item.setText(_translate("AboutRegion", "UMIDS"))
        item = self.EventsTable.item(0, 1)
        item.setText(_translate("AboutRegion", "20-я Международная выставка мебели, материалов, комплектующих и оборудования для деревообрабатывающего и мебельного производства"))
        item = self.EventsTable.item(0, 2)
        item.setText(_translate("AboutRegion", "29 марта –01 апреля 2016"))
        item = self.EventsTable.item(0, 3)
        item.setText(_translate("AboutRegion", "www.umids.ru"))
        item = self.EventsTable.item(1, 0)
        item.setText(_translate("AboutRegion", "Indecor Krasnodar"))
        item = self.EventsTable.item(1, 1)
        item.setText(_translate("AboutRegion", "2-я Выставка предметов интерьера и декора"))
        item = self.EventsTable.item(1, 2)
        item.setText(_translate("AboutRegion", "29 марта –01 апреля 2016"))
        item = self.EventsTable.item(1, 3)
        item.setText(_translate("AboutRegion", "www.indecor-krasnodar.ru"))
        item = self.EventsTable.item(2, 0)
        item.setText(_translate("AboutRegion", "Кубаньпродэкспо"))
        item = self.EventsTable.item(2, 1)
        item.setText(_translate("AboutRegion", "10-я Выставка продуктов питания и напитков производителей"))
        item = self.EventsTable.item(2, 2)
        item.setText(_translate("AboutRegion", "25 –27 апреля 2016"))
        item = self.EventsTable.item(2, 3)
        item.setText(_translate("AboutRegion", "www.kubanprodexpo.ru"))
        item = self.EventsTable.item(3, 0)
        item.setText(_translate("AboutRegion", "FoodTech Krasnodar"))
        item = self.EventsTable.item(3, 1)
        item.setText(_translate("AboutRegion", "19-я Выставка оборудования, материалов и ингредиентов для производства продуктов питания и напитков"))
        item = self.EventsTable.item(3, 2)
        item.setText(_translate("AboutRegion", "25 –27 апреля 2016"))
        item = self.EventsTable.item(3, 3)
        item.setText(_translate("AboutRegion", "foodtech-krasnodar.ru"))
        item = self.EventsTable.item(4, 0)
        item.setText(_translate("AboutRegion", "CleanExpo Krasnodar"))
        item = self.EventsTable.item(4, 1)
        item.setText(_translate("AboutRegion", "Международная выставка оборудования и материалов для профессиональной уборки, санитарии, гигиены, химической чистки и стирки"))
        item = self.EventsTable.item(4, 2)
        item.setText(_translate("AboutRegion", "25 –27 апреля 2016"))
        item = self.EventsTable.item(4, 3)
        item.setText(_translate("AboutRegion", "cleanexpo-krasnodar.ru"))
        item = self.EventsTable.item(5, 0)
        item.setText(_translate("AboutRegion", "InterFood Krasnodar"))
        item = self.EventsTable.item(5, 1)
        item.setText(_translate("AboutRegion", "6-я Выставка продуктов питания и напитков"))
        item = self.EventsTable.item(5, 2)
        item.setText(_translate("AboutRegion", "25 –27 апреля 2016"))
        item = self.EventsTable.item(5, 3)
        item.setText(_translate("AboutRegion", "www.inter-food.su"))
        self.EventsTable.setSortingEnabled(__sortingEnabled)

