# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExpertWindowUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ExpertWindow(object):
    def setupUi(self, ExpertWindow):
        ExpertWindow.setObjectName("ExpertWindow")
        ExpertWindow.resize(771, 533)
        self.centralwidget = QtWidgets.QWidget(ExpertWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        self.MainFrame.setGeometry(QtCore.QRect(20, 10, 761, 431))
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.MenuLabel = QtWidgets.QLabel(self.MainFrame)
        self.MenuLabel.setGeometry(QtCore.QRect(300, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MenuLabel.setFont(font)
        self.MenuLabel.setObjectName("MenuLabel")
        self.GreetLabel = QtWidgets.QLabel(self.MainFrame)
        self.GreetLabel.setGeometry(QtCore.QRect(300, 50, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GreetLabel.setFont(font)
        self.GreetLabel.setObjectName("GreetLabel")
        self.ResultsButton = QtWidgets.QPushButton(self.MainFrame)
        self.ResultsButton.setGeometry(QtCore.QRect(280, 250, 231, 111))
        self.ResultsButton.setObjectName("ResultsButton")
        self.EnterRatingsButton = QtWidgets.QPushButton(self.MainFrame)
        self.EnterRatingsButton.setGeometry(QtCore.QRect(280, 110, 231, 111))
        self.EnterRatingsButton.setObjectName("EnterRatingsButton")
        self.MarksFrame = QtWidgets.QFrame(self.centralwidget)
        self.MarksFrame.setGeometry(QtCore.QRect(19, 9, 741, 431))
        self.MarksFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MarksFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MarksFrame.setObjectName("MarksFrame")
        self.MCompetitorComboBox = QtWidgets.QComboBox(self.MarksFrame)
        self.MCompetitorComboBox.setGeometry(QtCore.QRect(390, 130, 73, 22))
        self.MCompetitorComboBox.setObjectName("MCompetitorComboBox")
        self.MCompetitorLabel = QtWidgets.QLabel(self.MarksFrame)
        self.MCompetitorLabel.setGeometry(QtCore.QRect(280, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MCompetitorLabel.setFont(font)
        self.MCompetitorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MCompetitorLabel.setObjectName("MCompetitorLabel")
        self.ModulLabel = QtWidgets.QLabel(self.MarksFrame)
        self.ModulLabel.setGeometry(QtCore.QRect(280, 170, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ModulLabel.setFont(font)
        self.ModulLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ModulLabel.setObjectName("ModulLabel")
        self.ModulComboBox = QtWidgets.QComboBox(self.MarksFrame)
        self.ModulComboBox.setGeometry(QtCore.QRect(390, 170, 73, 22))
        self.ModulComboBox.setObjectName("ModulComboBox")
        self.MarkLabel = QtWidgets.QLabel(self.MarksFrame)
        self.MarkLabel.setGeometry(QtCore.QRect(280, 210, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MarkLabel.setFont(font)
        self.MarkLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MarkLabel.setObjectName("MarkLabel")
        self.MarkComboBox = QtWidgets.QComboBox(self.MarksFrame)
        self.MarkComboBox.setGeometry(QtCore.QRect(390, 210, 73, 22))
        self.MarkComboBox.setObjectName("MarkComboBox")
        self.PushButton = QtWidgets.QPushButton(self.MarksFrame)
        self.PushButton.setGeometry(QtCore.QRect(310, 260, 161, 51))
        self.PushButton.setObjectName("PushButton")
        self.MBackButton = QtWidgets.QPushButton(self.MarksFrame)
        self.MBackButton.setGeometry(QtCore.QRect(0, 0, 101, 31))
        self.MBackButton.setObjectName("MBackButton")
        self.ResultsFrame = QtWidgets.QFrame(self.centralwidget)
        self.ResultsFrame.setGeometry(QtCore.QRect(19, 9, 741, 431))
        self.ResultsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ResultsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ResultsFrame.setObjectName("ResultsFrame")
        self.CompetitorComboBox = QtWidgets.QComboBox(self.ResultsFrame)
        self.CompetitorComboBox.setGeometry(QtCore.QRect(260, 110, 73, 22))
        self.CompetitorComboBox.setObjectName("CompetitorComboBox")
        self.CompetitorLabel = QtWidgets.QLabel(self.ResultsFrame)
        self.CompetitorLabel.setGeometry(QtCore.QRect(150, 110, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CompetitorLabel.setFont(font)
        self.CompetitorLabel.setObjectName("CompetitorLabel")
        self.SearchButton = QtWidgets.QPushButton(self.ResultsFrame)
        self.SearchButton.setGeometry(QtCore.QRect(450, 100, 141, 31))
        self.SearchButton.setObjectName("SearchButton")
        self.ResultsWidget = QtWidgets.QTableWidget(self.ResultsFrame)
        self.ResultsWidget.setGeometry(QtCore.QRect(130, 150, 231, 192))
        self.ResultsWidget.setObjectName("ResultsWidget")
        self.ResultsWidget.setColumnCount(0)
        self.ResultsWidget.setRowCount(0)
        self.RBackButton = QtWidgets.QPushButton(self.ResultsFrame)
        self.RBackButton.setGeometry(QtCore.QRect(0, 0, 101, 31))
        self.RBackButton.setObjectName("RBackButton")
        self.ThisChempionshipsLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.ThisChempionshipsLabel_4.setGeometry(QtCore.QRect(30, 450, 141, 16))
        self.ThisChempionshipsLabel_4.setObjectName("ThisChempionshipsLabel_4")
        self.NameChempionshipsLabel = QtWidgets.QLabel(self.centralwidget)
        self.NameChempionshipsLabel.setGeometry(QtCore.QRect(160, 450, 81, 16))
        self.NameChempionshipsLabel.setObjectName("NameChempionshipsLabel")
        self.ThisChempionshipsLabel_4.raise_()
        self.NameChempionshipsLabel.raise_()
        self.MainFrame.raise_()
        self.MarksFrame.raise_()
        self.ResultsFrame.raise_()
        ExpertWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ExpertWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 771, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        ExpertWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ExpertWindow)
        self.statusbar.setObjectName("statusbar")
        ExpertWindow.setStatusBar(self.statusbar)
        self.LogoutAction = QtWidgets.QAction(ExpertWindow)
        self.LogoutAction.setObjectName("LogoutAction")
        self.menu.addAction(self.LogoutAction)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(ExpertWindow)
        QtCore.QMetaObject.connectSlotsByName(ExpertWindow)

    def retranslateUi(self, ExpertWindow):
        _translate = QtCore.QCoreApplication.translate
        ExpertWindow.setWindowTitle(_translate("ExpertWindow", "MainWindow"))
        self.MenuLabel.setText(_translate("ExpertWindow", "Меню эксперта"))
        self.GreetLabel.setText(_translate("ExpertWindow", "Доброе утро, Имя"))
        self.ResultsButton.setText(_translate("ExpertWindow", "Просмотр результатов"))
        self.EnterRatingsButton.setText(_translate("ExpertWindow", "Ввод оценок"))
        self.MCompetitorLabel.setText(_translate("ExpertWindow", "Участник"))
        self.ModulLabel.setText(_translate("ExpertWindow", "Модуль"))
        self.MarkLabel.setText(_translate("ExpertWindow", "Оценка"))
        self.PushButton.setText(_translate("ExpertWindow", "Добавить оценку"))
        self.MBackButton.setText(_translate("ExpertWindow", "Назад"))
        self.CompetitorLabel.setText(_translate("ExpertWindow", "Участник"))
        self.SearchButton.setText(_translate("ExpertWindow", "Показать результаты"))
        self.RBackButton.setText(_translate("ExpertWindow", "Назад"))
        self.ThisChempionshipsLabel_4.setText(_translate("ExpertWindow", "Текущий чемпионат:"))
        self.NameChempionshipsLabel.setText(_translate("ExpertWindow", "название"))
        self.menu.setTitle(_translate("ExpertWindow", "Профиль"))
        self.LogoutAction.setText(_translate("ExpertWindow", "Выйти"))

